
export const LOGIN='LOGIN'
export const CONFIG='CONFIG'
export const CHECK_CAPTCH='CHECK_CAPTCH'
export const LOGOUT='LOGOUT'
// 查询条件
export const GET_GRADE="GET_GRADE"
export const GET_SUBJECT='GET_SUBJECT'
export const GET_TERM='GET_TERM'
export const GET_LEVEL='GET_LEVEL'
export const GET_YEAR='GET_YEAR'
export const GET_MATER='GET_MATER'
// 课程
export const GET_COURSE='GET_COURSE'
export const GET_COURSE_DETAIL='GET_COURSE_DETAIL'
export const GET_COURSE_CHAPTER='GET_COURSE_CHAPTER'
export const GET_COURSE_DATA='GET_COURSE_DATA'
// export const ADD_UPDATE_COURSE='ADD_UPDATE_COURSE'
// 讲次
export const GET_CHAPTER='GET_CHAPTER'
export const GET_CHAPTER_DETAIL='GET_CHAPTER_DETAIL'
// 素材
export const GET_DATA='GET_DATA'
export const GET_DATA_DETAIL='GET_DATA_DETAIL'
// office online
export const GET_TOKEN='GET_TOKEN'






export const SHOW_LOGIN_FORM='SHOW_LOGIN_FORM'
export const GET_INDEX='GET_INDEX'

export const CHANGE_WRITE='CHANGE_WRITE'

export const GET_QUESTION='GET_QUESTION'
export const GET_QUESTION_STATUS='GET_QUESTION_STATUS'
export const GET_QUESTION_TYPE='GET_QUESTION_TYPE'
export const CHANGE_PAGE='CHANGE_PAGE'
export const CHANGE_INPUT='CHANGE_INPUT'
export const GET_QUESTION_SOURCE='GET_QUESTION_SOURCE'
export const GET_SPP_LIST='GET_SPP_LIST'
export const GET_ABILITY='GET_ABILITY'
export const DEAL_ABILITY='DEAL_ABILITY'
export const GET_TREE='GET_TREE'

export const GET_USER_LIST='GET_USER_LIST'
export const GET_TREE_LIST='GET_TREE_LIST'
export const SAVE_TREE_DETAIL='SAVE_TREE_DETAIL'

export const GET_USER_DETAIL='GET_USER_DETAIL'
export const SAVE_OR_UPDATE_USER='SAVE_OR_UPDATE_USER'
export const GET_ORGANIZATION_BASE_CONFIG='GET_ORGANIZATION_BASE_CONFIG'
export const RESET_FORM='RESET_FORM'
export const DELETE_USER='DELETE_USER'

export const GET_CHARACTER_LIST='GET_CHARACTER_LIST'
export const GET_CHARACTER_DETAIL='GET_CHARACTER_DETAIL'
export const SAVE_OR_UPDATE_CHARACTER='SAVE_OR_UPDATE_CHARACTER'
export const DELETE_CHARACTER='DELETE_CHARACTER'

