
export const LOGIN='LOGIN'
export const CONFIG='CONFIG'
export const HAS_LOGIN='HAS_LOGIN'
export const SHOW_LOGIN_FORM='SHOW_LOGIN_FORM'
export const GET_INDEX='GET_INDEX'

export const CHANGE_WRITE='CHANGE_WRITE'

export const GET_QUESTION='GET_QUESTION'
export const GET_QUESTION_STATUS='GET_QUESTION_STATUS'
export const GET_QUESTION_TYPE='GET_QUESTION_TYPE'
export const CHANGE_PAGE='CHANGE_PAGE'
export const CHANGE_INPUT='CHANGE_INPUT'
export const GET_QUESTION_SOURCE='GET_QUESTION_SOURCE'
export const GET_SPP_LIST='GET_SPP_LIST'
export const GET_ABILITY='GET_ABILITY'
export const DEAL_ABILITY='DEAL_ABILITY'
export const GET_TREE='GET_TREE'

export const GET_USER_LIST='GET_USER_LIST'
export const GET_TREE_LIST='GET_TREE_LIST'
export const SAVE_TREE_DETAIL='SAVE_TREE_DETAIL'

export const GET_USER_DETAIL='GET_USER_DETAIL'
export const SAVE_OR_UPDATE_USER='SAVE_OR_UPDATE_USER'
export const GET_ORGANIZATION_BASE_CONFIG='GET_ORGANIZATION_BASE_CONFIG'
export const RESET_FORM='RESET_FORM'
export const DELETE_USER='DELETE_USER'

export const GET_CHARACTER_LIST='GET_CHARACTER_LIST'
export const GET_CHARACTER_DETAIL='GET_CHARACTER_DETAIL'
export const SAVE_OR_UPDATE_CHARACTER='SAVE_OR_UPDATE_CHARACTER'
export const DELETE_CHARACTER='DELETE_CHARACTER'

